name: build-live-json

on:
  schedule:
    - cron: "*/5 * * * *"           # cada 5 min
  workflow_dispatch:
  push:
    paths-ignore:
      - "live.json"                 # evita bucles al commitear live.json

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write               # necesario para git push
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generar live.json
        run: node scripts/build-live.mjs

      - name: Commit & push live.json
        run: |
          git config user.name  "pages-bot"
          git config user.email "pages-bot@users.noreply.github.com"
          git add live.json
          git commit -m "chore: update live.json [skip ci]" || echo "sin cambios"
          git push
