name: build-live-json

on:
  schedule:
    - cron: "*/5 * * * *"        # cada 5 min
  workflow_dispatch:              # ejecutarlo a mano
  push:
    paths-ignore:
      - "live.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Print Node version
        run: node -v

      - name: Generate live.json
        run: |
          set -e
          node build-live.mjs
          echo "Preview:"
          head -n 50 live.json || true

      - name: Commit & push live.json
        run: |
          git config user.name  "pages-bot"
          git config user.email "pages-bot@users.noreply.github.com"
          git add live.json
          git commit -m "chore: update live.json [skip ci]" || echo "sin cambios"
          git push || echo "push sin cambios"
